# Load UWB Data

In [2]:
import numpy as np 
import pandas as pd 
import uwb_dataset 
# import raw data 
columns, data = uwb_dataset.import_from_files() 
# divide CIR by RX preable count (get CIR of single preamble pulse) 
# item[2] represents number of acquired preamble symbols 
# for item in data:
#      item[15:] = item[15:]/float(item[2])

../dataset/uwb_dataset_part7.csv
../dataset/uwb_dataset_part2.csv
../dataset/uwb_dataset_part1.csv
../dataset/uwb_dataset_part3.csv
../dataset/uwb_dataset_part4.csv
../dataset/uwb_dataset_part5.csv
../dataset/uwb_dataset_part6.csv

# Create UWB(CIR) Pandas Dataframe

In [4]:
cir_n = len(columns[15:])

print("Columns :", columns, sep=" ")
print("Channel Impulse Response Count : ", cir_n, sep=" ")

Columns : ['NLOS' 'RANGE' 'FP_IDX' ... 'CIR1013' 'CIR1014' 'CIR1015']
Channel Impulse Response Count :  1016

In [16]:
df_uwb = pd.DataFrame(data=data, columns=columns)
# print(df_uwb['CH'])
print("Channel 2 count : ", df_uwb.query("CH == 2")['CH'].count())
print("Null/NaN Data Count :\n", df_uwb.isna().sum())
df_uwb.head()

Channel 2 count :  42000
Null/NaN Data Count :
 NLOS       0
RANGE      0
FP_IDX     0
FP_AMP1    0
FP_AMP2    0
          ..
CIR1011    0
CIR1012    0
CIR1013    0
CIR1014    0
CIR1015    0
Length: 1031, dtype: int64

,NLOS,RANGE,FP_IDX,FP_AMP1,FP_AMP2,FP_AMP3,STDEV_NOISE,CIR_PWR,MAX_NOISE,RXPACC,...,CIR1006,CIR1007,CIR1008,CIR1009,CIR1010,CIR1011,CIR1012,CIR1013,CIR1014,CIR1015
0,1.0,7.95,739.0,2450.0,5086.0,4373.0,64.0,8494.0,972.0,1024.0,...,242.0,219.0,453.0,426.0,341.0,520.0,180.0,176.0,333.0,0.0
1,0.0,5.87,744.0,5659.0,17056.0,16025.0,80.0,7635.0,1196.0,754.0,...,251.0,137.0,341.0,277.0,265.0,189.0,214.0,570.0,226.0,256.0
2,0.0,2.67,746.0,2969.0,11710.0,10296.0,44.0,10346.0,962.0,345.0,...,161.0,333.0,297.0,129.0,268.0,57.0,150.0,341.0,163.0,0.0
3,1.0,7.65,742.0,2311.0,4767.0,2830.0,76.0,11674.0,1140.0,1024.0,...,542.0,150.0,416.0,242.0,142.0,298.0,355.0,446.0,272.0,0.0
4,0.0,1.37,747.0,14088.0,5975.0,8700.0,92.0,12087.0,2376.0,274.0,...,220.0,170.0,255.0,272.0,67.0,85.0,182.0,190.0,279.0,0.0

In [21]:
# LOS/NLOS Count
los_count = df_uwb.query("NLOS == 0")['NLOS'].count()
nlos_count = df_uwb.query("NLOS == 1")['NLOS'].count()

print("Line of Sight count :", los_count)
print("Non Line of Sight count :", nlos_count)

Line of Sight count : 21000
Non Line of Sight count : 21000

In [23]:
# Columns CIR Extarct
df_uwb_data = df_uwb[["CIR"+str(i) for i in range(cir_n)]]
print("UWB DataFrame X for Trainndarray shape : ", df_uwb_data.values.shape)
df_uwb_data.head()

UWB DataFrame X for Trainndarray shape :  (42000, 1016)

,CIR0,CIR1,CIR2,CIR3,CIR4,CIR5,CIR6,CIR7,CIR8,CIR9,...,CIR1006,CIR1007,CIR1008,CIR1009,CIR1010,CIR1011,CIR1012,CIR1013,CIR1014,CIR1015
0,55.0,304.0,304.0,288.0,422.0,475.0,186.0,75.0,495.0,316.0,...,242.0,219.0,453.0,426.0,341.0,520.0,180.0,176.0,333.0,0.0
1,466.0,266.0,222.0,249.0,196.0,267.0,117.0,503.0,237.0,262.0,...,251.0,137.0,341.0,277.0,265.0,189.0,214.0,570.0,226.0,256.0
2,185.0,254.0,248.0,310.0,247.0,187.0,232.0,222.0,149.0,61.0,...,161.0,333.0,297.0,129.0,268.0,57.0,150.0,341.0,163.0,0.0
3,288.0,430.0,311.0,96.0,195.0,416.0,166.0,166.0,66.0,462.0,...,542.0,150.0,416.0,242.0,142.0,298.0,355.0,446.0,272.0,0.0
4,76.0,232.0,239.0,134.0,393.0,107.0,167.0,166.0,298.0,319.0,...,220.0,170.0,255.0,272.0,67.0,85.0,182.0,190.0,279.0,0.0

In [28]:
import pickle
temp_dict ={'data_t' : df_uwb, 'data_CIR' : df_uwb_data }
with open('dataset.pkl', 'wb') as f:
    pickle.dump(temp_dict, f, protocol=pickle.HIGHEST_PROTOCOL)

# with open('df_CIR.pkl', 'wb') as f:
#     pickle.dump(df_uwb_data)